import React from "react";
import { Modal, Form, Input, Select, DatePicker, InputNumber, Button, Space } from "antd";
import dayjs from "dayjs";
import { Transaction } from "../types";
import { formatNumber, parseFormattedNumber } from "../utils/format";
import { getCategories } from "../utils/categories";

const { TextArea } = Input;
const { Option } = Select;

interface AddTransactionModalProps {
  onSave: (transaction: Transaction) => void;
  onClose: () => void;
}

export const AddTransactionModal: React.FC<AddTransactionModalProps> = ({
  onSave,
  onClose,
}) => {
  const [form] = Form.useForm();
  const categories = getCategories();

  const handleSubmit = async () => {
    try {
      const values = await form.validateFields();
      const transaction: Transaction = {
        id: "", // Will be generated by parent
        merchant: values.merchant,
        amount: values.amount,
        currency: "IDR",
        date: dayjs(values.date).format("YYYY-MM-DD"),
        category: values.category || categories[0],
        summary: values.summary,
      };
      onSave(transaction);
      form.resetFields();
    } catch (error) {
      console.error("Validation failed:", error);
    }
  };

  return (
    <Modal
      title="Add Transaction"
      open={true}
      onCancel={onClose}
      footer={
        <Space>
          <Button onClick={onClose} id="close-add-modal-btn">Cancel</Button>
          <Button type="primary" onClick={handleSubmit} id="save-add-transaction-btn">
            Add Transaction
          </Button>
        </Space>
      }
      width={600}
    >
      <Form
        form={form}
        layout="vertical"
        initialValues={{
          date: dayjs(),
          category: categories[0],
        }}
      >
        <Form.Item
          label="Merchant"
          name="merchant"
          rules={[{ required: true, message: "Please enter merchant name" }]}
        >
          <Input id="add-merchant-input" />
        </Form.Item>

        <Form.Item
          label="Amount"
          name="amount"
          rules={[{ required: true, message: "Please enter amount" }]}
        >
          <InputNumber
            prefix="Rp"
            style={{ width: "100%" }}
            formatter={(value) => formatNumber(value || 0)}
            parser={(value) => parseFormattedNumber(value || "0")}
            id="add-amount-input"
          />
        </Form.Item>

        <Form.Item
          label="Date"
          name="date"
          rules={[{ required: true, message: "Please select date" }]}
        >
          <DatePicker style={{ width: "100%" }} format="YYYY-MM-DD" id="add-date-input" />
        </Form.Item>

        <Form.Item
          label="Category"
          name="category"
          rules={[{ required: true, message: "Please select category" }]}
        >
          <Select id="add-category-select">
            {categories.map((c) => (
              <Option key={c} value={c}>
                {c}
              </Option>
            ))}
          </Select>
        </Form.Item>

        <Form.Item
          label="Summary"
          name="summary"
          rules={[{ required: true, message: "Please enter summary" }]}
        >
          <TextArea rows={3} id="add-summary-input" />
        </Form.Item>
      </Form>
    </Modal>
  );
};
